.TH "_json_object_entry" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_json_object_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "json_char * \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBname_length\fP"
.br
.ti -1c
.RI "struct \fB_json_value\fP * \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
