.TH "config" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config \- test  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <people_counter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBkernel_1\fP"
.br
.ti -1c
.RI "int16_t \fBthreshold\fP"
.br
.ti -1c
.RI "uint8_t \fBmax_area\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
test 

//TODO add coments
.PP
o 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t config::kernel_1"
test 
.SS "uint8_t config::max_area"
test 
.SS "int16_t config::threshold"
test 

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
