.TH "json_state" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBused_memory\fP"
.br
.ti -1c
.RI "unsigned int \fBuint_max\fP"
.br
.ti -1c
.RI "unsigned long \fBulong_max\fP"
.br
.ti -1c
.RI "\fBjson_settings\fP \fBsettings\fP"
.br
.ti -1c
.RI "int \fBfirst_pass\fP"
.br
.ti -1c
.RI "const json_char * \fBptr\fP"
.br
.ti -1c
.RI "unsigned int \fBcur_line\fP"
.br
.ti -1c
.RI "unsigned int \fBcur_col\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
