.TH "json_settings" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_settings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBmax_memory\fP"
.br
.ti -1c
.RI "int \fBsettings\fP"
.br
.ti -1c
.RI "void *(* \fBmem_alloc\fP )(size_t, int zero, void *user_data)"
.br
.ti -1c
.RI "void(* \fBmem_free\fP )(void *, void *user_data)"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "size_t \fBvalue_extra\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
