.TH "mat" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mat \- the datastructure that represents the thermal image  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <people_counter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.RI "pointer to array of grayscale 8bit pixels "
.in -1c
.SH "Detailed Description"
.PP 
the datastructure that represents the thermal image 



.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
