.TH "object" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
object \- OBJECT (PERSON) STRUCT\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <people_counter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBid\fP"
.br
.ti -1c
.RI "\fBpixel\fP \fBcentroid\fP"
.br
.ti -1c
.RI "uint8_t \fBdisappeared_frames_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OBJECT (PERSON) STRUCT\&. 


.SH "Member Data Documentation"
.PP 
.SS "\fBpixel\fP object::centroid"
the center position of this object 
.SS "uint8_t object::disappeared_frames_count"
number of frames this object has disappered 
.SS "uint16_t object::id"
id of a tracked object 

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
