.TH "pixel" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel \- the structure that represent the position of a pixel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <people_counter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBx\fP"
.br
.RI "x coordinate of the pixel "
.ti -1c
.RI "uint8_t \fBy\fP"
.br
.RI "y coordinate of the pixel "
.in -1c
.SH "Detailed Description"
.PP 
the structure that represent the position of a pixel\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
