.TH "pixel" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBx\fP"
.br
.ti -1c
.RI "uint8_t \fBy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t pixel::x"
x coordinate of the pixel 
.SS "uint8_t pixel::y"
y coordinate of the pixel 

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
