.TH "queue" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBcount\fP"
.br
.ti -1c
.RI "uint8_t \fBtop\fP"
.br
.ti -1c
.RI "uint8_t \fBbottom\fP"
.br
.ti -1c
.RI "\fBpixel\fP \fBpixels\fP [QUEUE_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
