.TH "rec" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rec \- the struct that represents a rectangle  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <people_counter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBmin_x\fP"
.br
.RI "the minimum x coordinate of the rectangle "
.ti -1c
.RI "uint8_t \fBmin_y\fP"
.br
.RI "the minimum y coordiante of the rectangle "
.ti -1c
.RI "uint8_t \fBmax_x\fP"
.br
.RI "the maximum x coordiante of the rectangle "
.ti -1c
.RI "uint8_t \fBmax_y\fP"
.br
.RI "the maximum y coordinate of the rectangle "
.ti -1c
.RI "uint8_t \fBrid\fP"
.br
.RI "the id of the rectangle for distinguish the rectangle from the others in the same frame "
.ti -1c
.RI "uint16_t \fBarea\fP"
.br
.RI "the area of the rectagle(count of pixels) "
.in -1c
.SH "Detailed Description"
.PP 
the struct that represents a rectangle 

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
