.TH "recs" 3 "Fri Aug 7 2020" "Version 0.2" "People counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recs \- rectangles  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <people_counter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBcount\fP"
.br
.RI "the count of the rectangles "
.ti -1c
.RI "\fBrec\fP \fBnodes\fP [RECTS_MAX_SIZE]"
.br
.RI "the array that holds the rectangles "
.in -1c
.SH "Detailed Description"
.PP 
rectangles 

.SH "Author"
.PP 
Generated automatically by Doxygen for People counter from the source code\&.
